<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>..\..\app\target\desktop\src\main\resources\imgs\favicon.ico</ApplicationIcon>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <UseAppHost>true</UseAppHost>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.5-pre449"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0"/>
        <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
    </ItemGroup>

    <Target AfterTargets="AfterBuild" Name="CopyPresentMon" Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'True'">
        <ItemGroup>
            <RootFiles Include="$(ProjectDir)..\..\presentmon\*"/>
        </ItemGroup>

        <PropertyGroup>
            <PresentMonDestDir Condition="'$(PublishDir)' != ''">$(PublishDir)</PresentMonDestDir>
            <PresentMonDestDir Condition="'$(PresentMonDestDir)' == ''">$(TargetDir)\publish</PresentMonDestDir>
        </PropertyGroup>

        <Copy SourceFiles="@(RootFiles)" DestinationFolder="$(PresentMonDestDir)"/>
    </Target>

    <Target AfterTargets="AfterBuild" Name="CopyNativeToBin">
        <PropertyGroup>
            <SourceDir Condition="'$(PublishDir)' != ''">$(PublishDir)</SourceDir>
            <SourceDir Condition="'$(SourceDir)' == ''">$(TargetDir)\publish</SourceDir>
        </PropertyGroup>

        <ItemGroup>
            <Native Include="$(SourceDir)\*" Exclude="$(SourceDir)\libMonoPosixHelper.dylib"/>
        </ItemGroup>

        <PropertyGroup>
            <ArchFolder Condition="'$(RuntimeIdentifier)' == 'win-x64'">win-x64</ArchFolder>
            <ArchFolder Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">osx-arm64</ArchFolder>
            <ArchFolder Condition="'$(RuntimeIdentifier)' == 'linux-x64'">linux-x64</ArchFolder>
            <ArchFolder Condition="'$(ArchFolder)' == ''">$(RuntimeIdentifier)</ArchFolder>
        </PropertyGroup>

        <MakeDir Directories="$(ProjectDir)..\..\app\bin\$(ArchFolder)"/>
        <Copy SourceFiles="@(Native)" DestinationFolder="$(ProjectDir)..\..\app\bin\$(ArchFolder)"/>
    </Target>

</Project>
