name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'corretto'

    - name: Build with Gradle Wrapper
      run: cd app; ./gradlew :target:desktop:createDistributable

    - name: Zip distributable
      run: zip -r cleanmeter.zip target/desktop/build/compose/binaries/main/app
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cleanmeter.zip
        asset_name: cleanmeter
        tag: ${{ github.ref }}
        overwrite: false
        draft: true